#!/bin/sh

printf "Content-type: text/html\n\n"

input_pass="$(htmlpost2str "$(cat <&0)")"

if [ -z "$input_pass" ]; then
  [ -f "$PZ_LOGIN_FILE" ] && printf "authenticated"
  exit
fi

case "$input_pass" in
"bye")
  sudo shutdown now
  exit 0
  ;;
"help")
  find "$PZ_VAULT_DIR" -type f -exec shred -fuz '{}' \;
  exit 0
  ;;
*)
  hash="$(head -1 /etc/piz_hid-creds)"
  salt="$(head -2 /etc/piz_hid-creds | tail -1)"
  iter="$(tail -1 /etc/piz_hid-creds)"
  [ "$(piz_hid-hash "$input_pass" "$salt" "$iter")" = "$hash" ] && (
    umask 077
    printf "%s" "$input_pass" >"$PZ_LOGIN_FILE"
  )
  ;;
esac

[ -f "$PZ_LOGIN_FILE" ] && printf "authenticated"
