#!/bin/sh

printf "Content-type: text/html\n\n"

entry_sel="$(less <&0)"

if [ -z "$entry_sel" ]; then
  entry_sel="$(find "$PZ_VAULT_DIR" -type f ! -name ".gpg-id" |
    sed -e "s|^$PZ_VAULT_DIR||")"
  printf "%s" "$entry_sel"
else
  entry="$(sudo -u piz_hid gpg -d --batch --pinentry-mode loopback \
    --passphrase "$(cat "$PZ_LOGIN_FILE")" "$PZ_VAULT_DIR/$entry_sel" | sed 2q)"

  # username for clipboarding
  printf "%s" "$entry" | sed -n '2{p;q}'
  # type password out
  sudo piz_hid-keyboard 1 "$(printf "%s" "$entry" | sed 1q)"
fi
