#!/bin/sh

led0_dir="/sys/class/leds/led0"
#trigger_content="mmc0"

# Set the Pi Zero ACT LED trigger to 'none'.
printf "none" > "$led0_dir/trigger"

# Blink the ACT LED (1 - off, 0 - on)
printf  1 > "$led0_dir/brightness"
sleep 0.2
printf  0 > "$led0_dir/brightness"
sleep 0.1

printf 1 > "$led0_dir/brightness"
sleep 0.2
printf 0 > "$led0_dir/brightness"

# Restore trigger
#printf "%s" "$trigger_content" > "$led0_dir/trigger"
