#!/bin/sh

input_pass="$(htmlpost2str "$(cat <&0)")"

# Locked shutdown
if [ "$input_pass" = "bye" ]; then
  printf 'Content-type: text/html\n\n'
  sudo shutdown now
  exit 0
elif [ "$input_pass" = "help" ]; then
  vault_location="/piz_hid-vault/"
  printf 'Content-type: text/html\n\n'
  find "$vault_location" -type f -exec shred -fuz '{}' \;
  exit 0
fi

login_file="/piz_hid-login/pass"
if [ "$input_pass" ]; then
  hash="$(head -1 /etc/piz_hid-creds)"
  salt="$(head -2 /etc/piz_hid-creds | tail -1)"
  iter="$(tail -1 /etc/piz_hid-creds)"
  if [ "$(piz_hid-hash "$input_pass" "$salt" "$iter")" = "$hash" ]; then
    (
      umask 077
      printf "%s" "$input_pass" >"$login_file"
    )
  fi
fi

if [ -f "$login_file" ]; then
  printf 'Content-type: text/html\n\nauthenticated'
else
  printf 'Content-type: text/html\n\n'
fi
