#!/bin/sh

printf "Content-type: text/html\n\n"

input_pass="$(htmlpost2str "$(cat <&0)")"

if [ "$input_pass" = "bye" ]; then # Locked shutdown
  sudo shutdown now
elif [ "$input_pass" = "help" ]; then # Delete vault contents
  find "$PZ_VAULT_DIR" -type f -exec shred -fuz '{}' \;
elif [ "$input_pass" ]; then
  hash="$(head -1 /etc/piz_hid-creds)"
  salt="$(head -2 /etc/piz_hid-creds | tail -1)"
  iter="$(tail -1 /etc/piz_hid-creds)"
  if [ "$(piz_hid-hash "$input_pass" "$salt" "$iter")" = "$hash" ]; then
    (
      umask 077
      printf "%s" "$input_pass" >"$PZ_LOGIN_FILE"
    )
  fi
fi

if [ -f "$PZ_LOGIN_FILE" ]; then
  printf "authenticated"
fi
