#!/bin/sh


entry_sel="$(less <&0)"
vault_location="/piz_hid-vault/"

login="$(less /piz_hid-login/pass)"
entry="$(sudo -u piz_hid /usr/bin/gpg -d --batch --pinentry-mode loopback --passphrase "$login" "$vault_location/$entry_sel" | tail -n +2)"
printf "Content-type: text/html\n\n%s" "$entry"
