#!/bin/sh

printf "Content-type: text/html\n\n"

entry_sel="$(less <&0)"

if [ ! "$entry_sel" ]; then
  entry_sel="$(find "$PZ_VAULT_DIR" -type f ! -name ".gpg-id" |
    sed -e "s|^$PZ_VAULT_DIR||")"
  printf "%s" "$entry_sel"
else
  entry="$(sudo -u piz_hid gpg -d --batch --pinentry-mode loopback --passphrase "$(cat "$PZ_LOGIN_FILE")" "$PZ_VAULT_DIR/$entry_sel" |
    head -n 2)"

  # username for clipboarding
  printf "%s" "$(printf "%s" "$entry" | head -n 2 | tail -n 1)"
  # type password out
  sudo piz_hid-keyboard 1 "$(printf "%s" "$entry" | head -n 1)"
fi
