---
- name: Install network dep stuff
  ansible.builtin.apt:
    name:
      - isc-dhcp-server
      - isc-dhcp-common
      - dhcpcd5
      - hostapd
      - iptables
    state: present
- block:
  - name: Config DHCPCD
    copy:
      src: dhcpcd/dhcpcd.conf
      dest: /etc/dhcpcd.conf
  - name: Config DHCPCD to not wait on start
    copy:
      src: dhcpcd/no-wait.conf
      dest: /etc/systemd/system/dhcpcd.service.d/no-wait.conf
  - name: Enable DHCPCD service
    systemd:
      name: dhcpcd
      enabled: true
      masked: no
- block:
  - name: Config DHCPD
    copy:
      src: dhcpd/dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
  - name: Create leases file
    ansible.builtin.shell: sudo touch /var/lib/dhcp/dhcpd.leases
    args:
      creates: /var/lib/dhcp/dhcpd.leases
  - name: Install DHCPD4 service
    copy:
      src: dhcpd/dhcpd4.service
      dest: /etc/systemd/system/dhcpd4.service
  - name: Enable DHCPD service
    systemd:
      name: dhcpd4
      enabled: true
      masked: no
- block:
  - name: Config IPv4 ip forwarding
    copy:
      src: ap/sysctl.conf
      dest: /etc/sysctl.conf
  - name: Config hostapd
    copy:
      src: ap/hostapd.conf
      dest: /etc/hostapd.conf
  - name: Enable hostapd service
    systemd:
      name: hostapd
      enabled: true
      masked: no
